#ifndef ROCKSOLID_SDK_VERSION_H
#define ROCKSOLID_SDK_VERSION_H

/* Generated from sdk/VERSION. Do not edit this file manually. */

#define RS_SDK_VERSION_MAJOR 0
#define RS_SDK_VERSION_MINOR 2
#define RS_SDK_VERSION_PATCH 2
#define RS_SDK_VERSION_STRING "0.2.2"

#endif
