param(
  [string]$VersionFile = "sdk/VERSION",
  [string]$OutputHeader = "sdk/include/rocksolid_sdk_version.h"
)

$versionText = (Get-Content -LiteralPath $VersionFile -Raw).Trim()
if ($versionText -notmatch '^(\d+)\.(\d+)\.(\d+)$') {
  throw "Invalid SDK version '$versionText'. Expected semantic version format like 0.2.0."
}

$major = $Matches[1]
$minor = $Matches[2]
$patch = $Matches[3]

$content = @"
#ifndef ROCKSOLID_SDK_VERSION_H
#define ROCKSOLID_SDK_VERSION_H

/* Generated from sdk/VERSION. Do not edit this file manually. */

#define RS_SDK_VERSION_MAJOR $major
#define RS_SDK_VERSION_MINOR $minor
#define RS_SDK_VERSION_PATCH $patch
#define RS_SDK_VERSION_STRING "$versionText"

#endif
"@

Set-Content -LiteralPath $OutputHeader -Value $content -Encoding ascii
