param(
  [Parameter(Mandatory = $true)]
  [string]$PackageRoot,
  [Parameter(Mandatory = $true)]
  [ValidateSet("cpp", "capi")]
  [string]$PackageKind,
  [Parameter(Mandatory = $true)]
  [string]$Version
)

$cmakeDir = Join-Path $PackageRoot "cmake"
New-Item -ItemType Directory -Force -Path $cmakeDir | Out-Null

if ($PackageKind -eq "cpp") {
  $targetBlock = @'
get_filename_component(_rocksolid_sdk_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT TARGET RockSolidSDK::cpp_static)
  add_library(RockSolidSDK::cpp_static STATIC IMPORTED)
  set_target_properties(RockSolidSDK::cpp_static PROPERTIES
    IMPORTED_LOCATION "${_rocksolid_sdk_root}/lib/rocksolid_sdk_static.lib"
    INTERFACE_INCLUDE_DIRECTORIES "${_rocksolid_sdk_root}/include"
    INTERFACE_COMPILE_DEFINITIONS "RS_SDK_STATIC"
    INTERFACE_LINK_LIBRARIES "bcrypt;winhttp;ws2_32;crypt32"
  )
endif()
set(RockSolidSDK_PACKAGE_KIND "cpp")
'@
} else {
  $targetBlock = @'
get_filename_component(_rocksolid_sdk_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT TARGET RockSolidSDK::capi)
  add_library(RockSolidSDK::capi SHARED IMPORTED)
  set_target_properties(RockSolidSDK::capi PROPERTIES
    IMPORTED_IMPLIB "${_rocksolid_sdk_root}/lib/rocksolid_sdk.lib"
    IMPORTED_LOCATION "${_rocksolid_sdk_root}/bin/rocksolid_sdk.dll"
    INTERFACE_INCLUDE_DIRECTORIES "${_rocksolid_sdk_root}/include"
  )
endif()
set(RockSolidSDK_PACKAGE_KIND "capi")
'@
}

$configContent = @"
# Auto-generated by sdk/generate_cmake_package.ps1. Do not edit manually.
include_guard(GLOBAL)

set(RockSolidSDK_FOUND TRUE)
set(RockSolidSDK_VERSION "$Version")
$targetBlock
"@

$versionContent = @"
set(PACKAGE_VERSION "$Version")

if(PACKAGE_FIND_VERSION)
  if(PACKAGE_FIND_VERSION VERSION_GREATER PACKAGE_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
      set(PACKAGE_VERSION_EXACT TRUE)
    endif()
  endif()
endif()
"@

Set-Content -LiteralPath (Join-Path $cmakeDir "RockSolidSDKConfig.cmake") -Value $configContent -Encoding ascii
Set-Content -LiteralPath (Join-Path $cmakeDir "RockSolidSDKConfigVersion.cmake") -Value $versionContent -Encoding ascii
